### PR TITLE
small administrative stuff

### PR DESCRIPTION
**Pull request by jameslamb**
This PR takes care of some small administrative stuff that has been bugging me for a while.

1. Removed `elasticsearch` from file names. This package is all about Elasticsearch, those are unnecessary clutter
2. Renamed `utils.R` to `assertions.R` since the only function in there is an assertion. `utils` is pretty uninformative
3. Added stuff created by `covr::package_coverage()` to `.gitignore`

### CODE REVIEW

**Comment by jameslamb** [comment]
@austin3dickey good call, I'll break out those files right now

**Comment by jameslamb** [comment]
@austin3dickey I just split up all the source and testing files. Let me know what you think!

**Comment by austin3dickey** [comment]
Awesome!

**Comment by jameslamb** [comment]
this is building and looking good. Gonna merge it up!

**Pull request merged**
